### ISSUE TITLE
Add a shebang for Matlab

### ISSUE THREAD

**Issue by sebma** [niedzielski/shebang#2]
Hi,

Can you please add a shebang for Matlab scripts that calls `scriptName.m` this way : 

`matlab -nojvm -r "scriptName arg1 arg2 arg3 ...; exit"`

**Comment by niedzielski** [comment]
@sebma, sorry, I don't own MATLAB and I'm not sure what the syntax needed would be :[ This repo focuses on self-contained single file demos that echo the first argument passed to them (more guidelines [here](https://github.com/niedzielski/shebang#script-guidelines)). The idea is that if the simple demo can do this, one could specify whatever default arguments they wanted in a real world use case. Ideally, `#!/usr/bin/env` would support arbitrary numbers of arguments but it doesn't so this repo catalogs workarounds per language or tool.

I'm not very familiar with MATLAB these days but I think the example you've shown only demonstrates command line usage of MATLAB and not a self-executing script. If you wanted to convert this to be self-executing, you would need to find the official syntax that 1) ignores Bash constructs (e.g., [Perl](https://github.com/niedzielski/shebang/blob/master/demo/perl)) or 2) allows specifying command line arguments inline, or 3) figure out a workaround that processes a subset of the script as Bash that launches the real interpreter with the remainder (e.g., [node](https://github.com/niedzielski/shebang/blob/master/demo/node), [python](https://github.com/niedzielski/shebang/blob/master/demo/python)), or 4) something else :]
